debug node2 and network
Signed-off-by: vladimir.shishkin <vladimir.shishkin@evernym.com>

diff --git a/.github/workflows/node-ci.yml b/.github/workflows/node-ci.yml
--- a/.github/workflows/node-ci.yml
+++ b/.github/workflows/node-ci.yml
@@ -142,7 +142,7 @@ jobs:
           export HOME=/home/runner
           NODE5_PUBKEY=$(cheqd-noded tendermint show-validator | sed 's/\r//g')
           echo $NODE5_PUBKEY
-          curl "http://${NODE2_IP}:26657" || echo "Curl failed!"
           HOME=${{ env.NODE_CONFIGS_BASE }}/client cheqd-noded tx bank send ${OP0_ADDRESS} ${OP5_ADDRESS} 1000000000000000ncheq --chain-id cheqd --fees 5000000ncheq --node "http://${NODE2_IP}:26657" -y || echo "Send failed!"
+          curl "http://${NODE2_IP}:26657" || echo "Curl failed!"
           docker ps
           docker network inspect docker_compose_default
