debug
Signed-off-by: vladimir.shishkin <vladimir.shishkin@evernym.com>

diff --git a/.github/workflows/node-ci.yml b/.github/workflows/node-ci.yml
--- a/.github/workflows/node-ci.yml
+++ b/.github/workflows/node-ci.yml
@@ -119,7 +119,7 @@ jobs:
           sed -ri "s|laddr = \"tcp://0.0.0.0:26656\"|laddr = \"tcp://0.0.0.0:26676\"|" /home/runner/.cheqdnode/config/config.toml
           cat /home/runner/.cheqdnode/config/config.toml
           cheqd-noded start > /dev/null &
-          sleep 200
+          sleep 30
           docker ps
 
       - name: Promote observer to validator
@@ -140,7 +140,7 @@ jobs:
           export HOME=/home/runner
           NODE5_PUBKEY=$(cheqd-noded tendermint show-validator | sed 's/\r//g')
           echo $NODE5_PUBKEY
-          curl "http://${NODE0_IP}:26657"
+          curl "http://${NODE0_IP}:26657" || echo "Curl failed!"
+          HOME=${{ env.NODE_CONFIGS_BASE }}/client cheqd-noded tx bank send ${OP0_ADDRESS} ${OP5_ADDRESS} 1000000000000000ncheq --chain-id cheqd --fees 5000000ncheq --node "http://${NODE0_IP}:26657" -y
           docker ps
           docker network ls
-          HOME=${{ env.NODE_CONFIGS_BASE }}/client cheqd-noded tx bank send ${OP0_ADDRESS} ${OP5_ADDRESS} 1000000000000000ncheq --chain-id cheqd --fees 5000000ncheq --node "http://${NODE0_IP}:26657" -y
