debug
Signed-off-by: Vladimir Shishkin <vladimir.shishkin@dsr-corporation.com>

diff --git a/.github/workflows/node-ci.yml b/.github/workflows/node-ci.yml
--- a/.github/workflows/node-ci.yml
+++ b/.github/workflows/node-ci.yml
@@ -220,4 +220,5 @@ jobs:
         run: |
           export OP0_ADDRESS=""
           export OP1_ADDRESS=""
-          pytest -v -rP tests/e2e/test_identity.py::test_did_positive
+          pytest -v -rP tests/e2e/test_identity.py::test_did_positive || echo "Fail!"
+          ls -la $HOME/.indy_client
