enable logs
Signed-off-by: Vladimir Shishkin <vladimir.shishkin@dsr-corporation.com>

diff --git a/.github/workflows/node-ci.yml b/.github/workflows/node-ci.yml
--- a/.github/workflows/node-ci.yml
+++ b/.github/workflows/node-ci.yml
@@ -220,5 +220,5 @@ jobs:
         run: |
           export OP0_ADDRESS=""
           export OP1_ADDRESS=""
-          pytest -v -rP tests/e2e/test_identity.py::test_did_positive 2>&1 > log.txt
+          pytest -v -rP tests/e2e/test_identity.py::test_did_positive 2>&1 > log.txt || echo "Fail!"
           cat log.txt
