Review comments

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -24,14 +24,13 @@ jobs:
           cache: true
 
       - name: Install ginkgo
-        run: |
-          go install github.com/onsi/ginkgo/v2/ginkgo
-          go get github.com/onsi/gomega/...
+        working-directory: ./..
+        run: go install github.com/onsi/ginkgo/v2/ginkgo@latest
 
-      # - name: Run Ginkgo tests
-      #   run: ginkgo -r --race --randomize-all --randomize-suites --junit-report report.xml
+      - name: Run Ginkgo tests
+        run: ginkgo -r --race --randomize-all --randomize-suites --junit-report report.xml
 
-      # - uses: mikepenz/action-junit-report@v3
-      #   if: success() || failure()        # run this step even if previous step failed
-      #   with:
-      #     report_paths: 'report.xml'
+      - uses: mikepenz/action-junit-report@v3
+        if: success() || failure()        # run this step even if previous step failed
+        with:
+          report_paths: 'report.xml'
