Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -23,15 +23,14 @@ jobs:
           cache: true
 
       - name: Install ginkgo
-        working-directory: ./..
         run: |
-          go install github.com/onsi/ginkgo/v2/ginkgo@latest
-          go install github.com/jstemmer/go-junit-report/v2@latest
+          go get github.com/onsi/ginkgo/v2/ginkgo
+          go get github.com/onsi/gomega/...
 
       - name: Run Ginkgo tests
         run: ginkgo -r --race --randomize-all --randomize-suites --junit-report report.xml
 
-      - uses: mikepenz/action-junit-report@v3
-        if: success() || failure()
-        with:
-          report_paths: 'report.xml'
+      # - uses: mikepenz/action-junit-report@v3
+      #   if: success() || failure()        # run this step even if previous step failed
+      #   with:
+      #     report_paths: 'report.xml'
