Added test reporting (testing)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,5 +1,16 @@
 name: "Test"
 on:
+  pull_request_target:
+    branches:
+      - main
+      - develop
+    types:
+      - opened
+      - reopened
+      - edited
+      - synchronize
+      - ready_for_review
+      - review_requested
   workflow_call:
     inputs:
       VERSION:
@@ -11,8 +22,9 @@ defaults:
 env:
   NODE_CONFIGS_BASE: "/home/runner/work/cheqd-node/cheqd-node/docker/localnet/network-config"
 permissions:
+  id-token: write
   contents: write
-  packages: read
+  checks: write
 
 jobs:
   ginkgo-tests:
@@ -31,11 +43,23 @@ jobs:
         run: |
           go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
           go get github.com/onsi/gomega/...
+          go install github.com/jstemmer/go-junit-report/v2@latest
 
       - name: Run Ginkgo tests
-        run: ginkgo -r --race --randomize-all --randomize-suites -v
+        run: |
+          go test -v github.com/cheqd/cheqd-node/x/cheqd/utils 2>&1 | go-junit-report -parser gotest > report.xml
+#
+      - uses: dorny/test-reporter@v1
+        if: success() || failure()        # run this step even if previous step failed
+        with:
+          name: JEST Tests                  # Name of the check run which will be created
+          path: report.xml                     # Path to test results (inside artifact .zip)
+          reporter: java-junit              # Format of test results
+          max-annotations: '50'
+          fail-on-error: false
 
-  # test-new-node-setup:
+
+    # test-new-node-setup:
   #   name: "New node setup"
   #   runs-on: ubuntu-latest
   #   env:
@@ -278,4 +302,3 @@ jobs:
   #     - name: Check that node with Cosmovisor was upgraded
   #       working-directory: ./tests/e2e-complex/upgrade/cosmovisor
   #       run: START_HEIGHT=${{ steps.initiate-upgrade.outputs.START_HEIGHT }} bash check_upgrade.sh
-
