Squashed commit of the following:
commit 403f5bca9f815337fd89231f0a970a5508207b87
Author: Ankur Banerjee <ankurdotb@users.noreply.github.com>
Date:   Tue Oct 18 15:21:54 2022 +0100

    ci: Update CI workflows

commit 208cad00b6d3a7e546b705276409457a53f7c5b9
Author: Ankur Banerjee <ankurdotb@users.noreply.github.com>
Date:   Tue Oct 18 14:33:03 2022 +0100

    ci: Reset workflow dispatch to use local workflow copy

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -58,6 +58,10 @@ jobs:
         run: |
           go install github.com/onsi/ginkgo/v2/ginkgo@latest
 
-      - name: Run tests
-        run: |
-          ginkgo -r --tags integration tests/integration
+      # - name: Run Ginkgo tests
+      #   run: ginkgo -r --race --randomize-all --randomize-suites --junit-report report.xml
+
+      # - uses: mikepenz/action-junit-report@v3
+      #   if: success() || failure()        # run this step even if previous step failed
+      #   with:
+      #     report_paths: 'report.xml'
